### ISSUE TITLE
DS01C dimmer 

### ISSUE THREAD

**Issue by graphite-elegance** [jasonyork/config#1]
I found you through a post you made on Digiblur's site about the tuya dimmer. I bought a bunch of these because the first one that I purchase was able to be flashed with tuya convert, so I bought 16 of them and now they wont flash with tuya-convert, newest version and I cant seem to get them to flash by connecting directly.  I am wondering how you set yours up and got it to flash. Did you cut the traces for the secondary MCU? or ??? 

I would really appreciate any suggestions.

Thanks 
Todd Harris

**Comment by jasonyork** [comment]
@graphite-elegance - Hey Todd.  I flashed them directly by soldering wires on the processor like Digiblur showed in his video here: https://www.youtube.com/watch?v=fyxxk2NrKG8&feature=youtu.be&t=112
I did not need to cut any traces.  I only had two of them, so It wasn't too bad.  I actually didn't end up using them though because the dimmer caused a loud hum with the LED fixture I was using.  I'll probably try them somewhere else later with a different light to see if the hum persists.
Good luck!

**Comment by vajonam** [comment]
> I found you through a post you made on Digiblur's site about the tuya dimmer. I bought a bunch of these because the first one that I purchase was able to be flashed with tuya convert, so I bought 16 of them and now they wont flash with tuya-convert, newest version and I cant seem to get them to flash by connecting directly. I am wondering how you set yours up and got it to flash. Did you cut the traces for the secondary MCU? or ???
> 
> I would really appreciate any suggestions.
> 
> Thanks
> Todd Harris

@graphite-elegance were you able to flash these dimmers? I am struggling with it too. Before I cut traces wanted to see if there was an easier way.

**Comment by graphite-elegance** [comment]
Hey, sorry for the delay but the ones I bought were able to be flashed with a newer version of tuya convert after I attempted to cut the traces and failed.

 

I did find this video from Digiblur that he shows flashing them without cutting any traces. You may want to follow his video…

 

https://www.youtube.com/watch?v=JE3vWB-rhFM

 

Good luck

**Comment by vajonam** [comment]
@graphite-elegance yup sorted it out with cp2102 flasher...
